# Passel Type
vb_passel_type_index:
    path: /types
    host: passels.{domain}
    defaults:
        _controller: VolleyballPasselBundle:PasselType:index
        page: 1
    requirements:
        page: \d+
        domain: %domain%
vb_passel_type_index_by_organization:
    path: /{slug}/passel-types
    host: organizations.{domain}
    defaults:
        _controller: VolleyballPasselBundle:PasselType:index
        page: 1
    requirements:
        page: \d+
        slug: +s
        domain: %domain%
vb_passel_type_show:
    path: /types/{slug}
    host: passels.{domain}
    defaults:
        _controller: VolleyballPasselBundle:PasselType:show
        page: 1
    requirements:
        page: \d+
        domain: %domain%
vb_passel_type_edit:
    path: /types/{slug}/edit
    host: passels.{domain}
    defaults: { _controller: VolleyballPasselBundle:PasselType:edit }
    requirements:
        slug: +s
        domain: %domain%

